$(eval $(call addlib,appodinhello))

APPODINHELLO_SRCS-y += $(APPODINHELLO_BASE)/hello.odin

# Odin compiler
ODIN ?= odin

ifeq ($(CONFIG_ARCH_X86_64),y)
ODIN_TARGET := linux_amd64
else ifeq ($(CONFIG_ARCH_ARM_64),y)
ODIN_TARGET := linux_arm64

endif

#  build rule for .odin files
define buildrule_odin =
$(4): $(2)
	$(call build_cmd,ODIN,$(1),$(4),\
		$(ODIN) build $(2) \
			-file \
			-build-mode:obj \
			-out:$(4) \
			-target:$(ODIN_TARGET) \
			-o:size \
			-reloc-mode:pic \
			-default-to-nil-allocator \
		&& { test -f $(4) || { echo "Odin dev-2026-08 or newer is required"; false; }; })

UK_OBJS-y += $(4)
$(eval $(call vprefix_lib,$(1),OBJS-y) += $(4))
$(eval $(call vprefix_lib,$(1),CLEAN-y) += $(call build_clean,$(4)))
endef
